name: Upload Website

on: [workflow_dispatch]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up Node
        uses: actions/setup-node@v1
        working-directory: ./client
        with:
          node-version: "16.x"
      - run: npm install
      - run: npm run build
      - run: npm run deploy